[project]
name = "conversion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub==0.36.0",
    "torchvision>=0.24.1",
]
